catalog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page, never_cache

from catalog.apps import CatalogConfig
from catalog.views import HomeView, ContactsView, ProductDetailView, ProductListView, ProductDeleteView, \
    ProductCreateView, \
    ProductUpdateView, BlogRecordListView, \
    BlogRecordDetailView, BlogRecordCreateView, BlogRecordUpdateView, BlogRecordDeleteView, \
    BlogRecordDeactivatedListView, toggle_activity, VersionDetailView, VersionListView, VersionCreateView, CategoryListView

app_name = CatalogConfig.name

urlpatterns = [
    path('', HomeView.as_view(), name='homepage'),
    path('products/', ProductListView.as_view(), name='products_list'),
    path('contacts/', ContactsView.as_view(), name='contacts'),
    path('product/<int:pk>/', cache_page(60)(ProductDetailView.as_view()), name='product_detail'),
    path('product/create/', never_cache(ProductCreateView.as_view()), name='product_create'),
    path('product/update/<int:pk>/', never_cache(ProductUpdateView.as_view()), name='product_update'),
    path('product/delete/<int:pk>/', never_cache(ProductDeleteView.as_view()), name='product_delete'),
    path('category_list/', CategoryListView.as_view(), name='category_list'),
    path('version/create/', never_cache(VersionCreateView.as_view()), name='version_create'),
    path('version/<int:pk>/', VersionDetailView.as_view(), name='version_detail'),
    path('blog_records/', BlogRecordListView.as_view(), name='blog_records'),
    path('blog_records_deactivated/', BlogRecordDeactivatedListView.as_view(), name='blog_records_deactivated'),
    path('blog_records/<slug:slug>/', BlogRecordDetailView.as_view(), name='blog_record_detail'),
    path('blog_record/create/', never_cache(BlogRecordCreateView.as_view()), name='blog_record_create'),
    path('blog_record/update/<slug:slug>/', never_cache(BlogRecordUpdateView.as_view()), name='blog_record_update'),
    path('blog_record/delete/<slug:slug>/', never_cache(BlogRecordDeleteView.as_view()), name='blog_record_delete'),
    path('blog_record/toggle/<slug:slug>/', toggle_activity, name='toggle_activity'),
]

config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page, never_cache

from users.apps import UsersConfig
from users.views import LoginView, LogoutView, RegisterView, UserUpdateView, generate_new_password

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', never_cache(RegisterView.as_view()), name='register'),
    path('profile/', never_cache(UserUpdateView.as_view()), name='profile'),
    path('profile/genpassword/', never_cache(generate_new_password), name='generate_new_password'),
]

catalog/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings

NULLABLE = {'blank': True, 'null': True}


class Category(models.Model):
    name = models.CharField(max_length=150, verbose_name='наименование')  # обязательно
    description = models.TextField(verbose_name='описание', **NULLABLE)

    # category_created_at = models.DateTimeField(verbose_name='дата создания', auto_now_add=True, **NULLABLE)

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'категория'
        verbose_name_plural = 'категории'
        ordering = ('name',)


class Product(models.Model):
    name = models.CharField(max_length=150, verbose_name='наименование')  # обязательно
    description = models.TextField(verbose_name='описание', **NULLABLE)
    image = models.ImageField(upload_to='images/products/', verbose_name='изображение(превью)', **NULLABLE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='категория')  # обязательно
    price = models.PositiveIntegerField(verbose_name='цена за покупку')
    created = models.DateField(verbose_name='дата создания', auto_now_add=True, **NULLABLE)
    updated = models.DateField(verbose_name='дата последнего изменения', auto_now=True, **NULLABLE)
    is_active = models.BooleanField(default=False, verbose_name='активный')

    creator = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, **NULLABLE,
                                verbose_name='создатель')

    def __str__(self):
        return f'{self.name}'

    pass

    class Meta:
        verbose_name = 'продукт'
        verbose_name_plural = 'продукты'
        ordering = ('name',)


class Version(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='продукт')
    number = models.IntegerField(verbose_name='номер версии')
    name = models.CharField(max_length=150, verbose_name='название версии')
    sign_of_current_version = models.BooleanField(default=False, verbose_name='активный')

    def __str__(self):
        return f'{self.product} {self.number}'

    class Meta:
        verbose_name = 'версия'
        verbose_name_plural = 'версии'
        ordering = ('number',)


class BlogRecord(models.Model):
    title = models.CharField(max_length=150, verbose_name='Заголовок')
    slug = models.SlugField(max_length=300, unique=True, db_index=True, verbose_name="URL")
    content = models.TextField(verbose_name='Содержимое')
    preview = models.ImageField(upload_to='images/records/', verbose_name='изображение(превью)', **NULLABLE)
    created = models.DateField(verbose_name='дата создания', auto_now_add=True)
    sign_of_publication = models.BooleanField(default=True, verbose_name='активный')
    views = models.IntegerField(default=0)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, **NULLABLE, verbose_name='автор')

    def __str__(self):
        return f"{self.title}, {self.created}"

    def get_absolute_url(self):
        return reverse('catalog:blog_record_detail', kwargs={'slug': self.slug})

    class Meta:
        verbose_name = 'Запись'
        verbose_name_plural = 'Записи'
        get_latest_by = 'created'

    def views_count(self):
        self.views += 1
        self.save()

catalog/forms.py
from django import forms

from catalog.models import Product, BlogRecord, Version


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class ProductForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Product
        exclude = ('created', 'updated', 'creator',)

    def clean_name(self):
        cleaned_data = self.cleaned_data['name']
        banned_names_list = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция',
                             'радар']
        if cleaned_data.lower() in banned_names_list:
            raise forms.ValidationError(f'Наименование {cleaned_data} запрещено к использованию')
        return cleaned_data


class VersionForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Version
        fields = '__all__'

    # def clean_sign_of_current_version(self):
    #     cleaned_data = self.cleaned_data['sign_of_current_version']
    #     if cleaned_data:
    #         return cleaned_data
    #     else:
    #         return "Версия неактивна"


class BlogRecordForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = BlogRecord
        fields = ('title', 'slug', 'content', 'preview')

catalog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.forms import inlineformset_factory
from django.http import Http404

from catalog.services import send_email
from catalog.models import Product, BlogRecord, Version, Category
from django.views import generic
from django.urls import reverse_lazy
from django.shortcuts import render, get_object_or_404, reverse, redirect
from catalog.forms import BlogRecordForm, ProductForm, VersionForm
from catalog.services import get_cached_category_subjects


class HomeView(LoginRequiredMixin, generic.TemplateView):
    """Контроллер для работы с домашней страницей, показывает только 4 первых продукта"""
    template_name = 'catalog/home.html'
    extra_context = {
        'object_list': Product.objects.all()[:4],
        'title': 'Домашняя страница'
    }


class CategoryListView(LoginRequiredMixin, generic.ListView):
    model = Category
    extra_context = {
        'title': 'Категории продуктов',
    }

    def get_context_data(self, **kwargs):
        """Переопределение метода, логика прописана в services.py"""
        context_data = super().get_context_data(**kwargs)
        context_data['category_list'] = get_cached_category_subjects()
        return context_data


class ProductListView(LoginRequiredMixin, generic.ListView):
    """Контроллер для работы со страницей, со всеми продуктами"""
    model = Product
    extra_context = {
        'title': 'Каталог'
    }


# def home(request):
#     context = {
#         'object_list': Product.objects.all(),
#         'title': 'Каталог'
#     }
#     return render(request, 'catalog/home.html', context)


class ProductDetailView(LoginRequiredMixin, generic.DetailView):
    """Контроллер для работы со страницей продукта (подробная информация о продукте)"""
    model = Product

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['title'] = self.get_object()
        return context_data


# def product(request, pk):
#     product_item = Product.objects.get(pk=pk)
#     context = {
#         'object': product_item,
#         'title': product_item.name
#     }
#     return render(request, 'catalog/product.html', context)

class ProductCreateView(LoginRequiredMixin, generic.CreateView):
    """Контроллер для создания продукта"""
    model = Product
    form_class = ProductForm

    def get_success_url(self):
        return reverse('catalog:products_list')

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        ParentFormset = inlineformset_factory(Product, Version, form=VersionForm, extra=1)
        if self.request.method == 'POST':
            formset = ParentFormset(self.request.POST, instance=self.object)
        else:
            formset = ParentFormset(instance=self.object)
        context_data['formset'] = formset
        return context_data

    def form_valid(self, form):
        context_data = self.get_context_data()
        formset = context_data['formset']
        self.object = form.save()
        if formset.is_valid():
            formset.instance = self.object
            formset.save()
        self.object.creator = self.request.user
        self.object.save()
        return super().form_valid(form)


class ProductUpdateView(LoginRequiredMixin, generic.UpdateView):
    """Контроллер для обновления продукта"""
    model = Product
    form_class = ProductForm

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.object.creator != self.request.user and not self.request.user.is_staff:
            raise Http404
        return self.object

    def get_success_url(self):
        return reverse('catalog:product_update', args=[self.kwargs.get('pk')])

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        ParentFormset = inlineformset_factory(Product, Version, form=VersionForm, extra=1)
        if self.request.method == 'POST':
            formset = ParentFormset(self.request.POST, instance=self.object)
        else:
            formset = ParentFormset(instance=self.object)
        context_data['formset'] = formset
        return context_data

    def form_valid(self, form):
        context_data = self.get_context_data()
        formset = context_data['formset']
        self.object = form.save()

        if formset.is_valid():
            formset.instance = self.object
            formset.save()
        return super().form_valid(form)


class ProductDeleteView(LoginRequiredMixin, generic.DeleteView):
    """Контроллер для удаления продукта"""
    model = Product
    success_url = reverse_lazy('catalog:products_list')


class VersionListView(LoginRequiredMixin, generic.ListView):
    model = Version
    extra_context = {
        'title': 'Список активных версий',
    }

    def get_queryset(self):
        """Метод благодаря которому отображаются только активные записи"""
        queryset = super().get_queryset()
        queryset = queryset.filter(sign_of_current_version=True)
        return queryset


class VersionCreateView(LoginRequiredMixin, generic.CreateView):
    model = Version
    form_class = ProductForm
    success_url = reverse_lazy('catalog:products_list')


class VersionUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Version
    form_class = VersionForm
    success_url = reverse_lazy('catalog:products_list')


class VersionDetailView(LoginRequiredMixin, generic.DetailView):
    model = Version

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['title'] = self.get_object()
        return context_data


class ContactsView(LoginRequiredMixin, generic.TemplateView):
    """Контроллер для работы страницы с контактами"""
    template_name = 'catalog/contacts.html'
    extra_context = {
        'title': 'Контакты'
    }

    def post(self, request, *args, **kwargs):
        """Метод для отправки данных пост запросом на сервер"""
        name = request.POST.get('name', '')
        phone = request.POST.get('phone', '')
        message = request.POST.get('message', '')
        print(f'User {name}, with phone {phone}, send message: {message}')
        return render(request, self.template_name)


# def contacts(request):
#    if request.method == "POST":
#        name = request.POST.get('name')
#        phone = request.POST.get('phone')
#        message = request.POST.get('message')
#        print(f'User {name}, with phone {phone}, send message: {message}')
#    return render(request, 'catalog/contacts.html')

class BlogRecordListView(LoginRequiredMixin, generic.ListView):
    """Контроллер для отображения блоговых записей"""
    model = BlogRecord
    extra_context = {
        'title': 'Список записей'
    }

    def get_queryset(self):
        """Метод благодаря которому отображаются только активные записи"""
        queryset = super().get_queryset()
        queryset = queryset.filter(sign_of_publication=True)
        return queryset


class BlogRecordDeactivatedListView(LoginRequiredMixin, generic.ListView):
    """Контроллер для отображения блоговых записей"""
    model = BlogRecord
    extra_context = {
        'title': 'Список деактивированных записей'
    }

    def get_queryset(self):
        """Метод благодаря которому отображаются только неактивные записи"""
        queryset = super().get_queryset()
        queryset = queryset.filter(sign_of_publication=False)
        return queryset


class BlogRecordDetailView(LoginRequiredMixin, generic.DetailView):
    """Контроллер для отображения одной блоговой записи в подробностях"""
    model = BlogRecord

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        # context_data['title'] = context_data['object']
        context_data['title'] = self.get_object()
        object = self.get_object()
        increase = get_object_or_404(BlogRecord, pk=object.pk)
        increase.views_count()
        if increase.views == 100:
            send_email(increase)
        return context_data


class BlogRecordCreateView(LoginRequiredMixin, PermissionRequiredMixin, generic.CreateView):
    """Контроллер для создания блоговой записи"""
    model = BlogRecord
    form_class = BlogRecordForm
    permission_required = 'catalog.add_blogrecord'
    success_url = reverse_lazy('catalog:blog_records')

    def form_valid(self, form):
        self.object = form.save()
        self.object.author = self.request.user
        self.object.save()

        return super().form_valid(form)


class BlogRecordUpdateView(LoginRequiredMixin, PermissionRequiredMixin, generic.UpdateView):
    """Контроллер для обновления блоговой записи"""
    model = BlogRecord
    form_class = BlogRecordForm
    permission_required = 'catalog.change_blogrecord'
    success_url = reverse_lazy('catalog:blog_records')


class BlogRecordDeleteView(LoginRequiredMixin, PermissionRequiredMixin, generic.DeleteView):
    """Контроллер для удаления блоговой записи"""
    model = BlogRecord
    permission_required = 'catalog.delete_blogrecord'
    success_url = reverse_lazy('catalog:blog_records')


def toggle_activity(request, slug):
    blog_record_item = get_object_or_404(BlogRecord, slug=slug)
    if blog_record_item.sign_of_publication:
        blog_record_item.sign_of_publication = False
    else:
        blog_record_item.sign_of_publication = True
    blog_record_item.save()
    return redirect(reverse('catalog:blog_records'))

catalog/templates/catalog/includes/inc_blogrecord_form.html
{% load mediapath %}
<div class="col-3">
    <div class="card mb-4 box-shadow">
        <div class="card-header">
            <h4 class="my-0 font-weight-normal">{{ object.title }}</h4>
        </div>
        <div class="card-body">
            <img src="{% mediapath object.preview %}" alt="Изображение" width="200" height="150"/>
            <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                <li> {{ object.content|truncatechars:45 }} </li>
            </ul>
            <a class="btn btn-lg btn-block btn-outline-info"
               href="{% url 'catalog:blog_record_detail' object.slug %}">Подробнее</a>
            {% if perms.catalog.change_blogrecord and perms.catalog.delete_blogrecord %}
                <a href="{% url 'catalog:blog_record_update' object.slug %}"
                   class="btn btn-lg btn-block btn-outline-warning">Изменить/Удалить</a>
            {% elif perms.catalog.change_blogrecord %}
                <a href="{% url 'catalog:blog_record_update' object.slug %}"
                   class="btn btn-lg btn-block btn-outline-warning">Изменить</a>
            {% endif %}
            {% if perms.catalog.change_blogrecord %}
                <a href="{% url 'catalog:toggle_activity' object.slug %}"
                   class="btn btn-lg btn-block btn-outline-secondary">
                {% if object.sign_of_publication %}
                    Деактивировать
                {% else %}
                    Активировать
                {% endif %}
            {% endif %}
            </a>
        </div>
    </div>
</div>

catalog/templates/catalog/includes/inc_catalog_info.html
<div class="row">
    <div class="col-12 col-md">
        SkyStore
        <small class="d-block mb-3 text-muted">&copy; 2023</small>
    </div>
    <div class="col-6 col-md">
        <h5>Категории</h5>
        <ul class="list-unstyled text-small">
            <li><a class="text-muted" href="#">Рассылки</a></li>
            <li><a class="text-muted" href="#">Телеграм боты</a></li>
            <li><a class="text-muted" href="#">Полезные утилиты</a></li>
            <li><a class="text-muted" href="#">Веб-приложения</a></li>
            <li><a class="text-muted" href="#">Микросервисы</a></li>
        </ul>
    </div>
    <div class="col-6 col-md">
        <h5>Дополнительно</h5>
        <ul class="list-unstyled text-small">
            <li><a class="text-muted" href="#">Мы пишем</a></li>
        </ul>
    </div>
    <div class="col-6 col-md">
        <h5>О нас</h5>
        <ul class="list-unstyled text-small">
            <li><a class="text-muted" href="/contacts/">Контакты</a></li>
        </ul>
    </div>
</div>

catalog/templates/catalog/includes/inc_catalog_menu.html
<h5 class="my-0 mr-md-auto font-weight-normal">Skystore</h5>
<nav class="ms-5">
    <a class="p-2 btn btn-outline-primary" href="/">Домашняя страница</a>
    <a class="p-2 btn btn-outline-primary" href="/category_list/">Категории</a>
    <a class="p-2 btn btn-outline-primary" href="/products/">Все продукты</a>
    <a class="p-2 btn btn-outline-primary" href="/blog_records/">Записи</a>
    <a class="p-2 btn btn-outline-primary" href="/contacts/">Контакты</a>
    {% if user.is_authenticated %}
        <a href="{% url 'users:profile' %}" class="p-2 btn btn-outline-primary">Профиль</a>
        <a href="{% url 'users:logout' %}" class="p-2 btn btn-outline-primary">Выход</a>
    {% else %}
        <a href="{% url 'users:login' %}" class="p-2 btn btn-outline-primary">Вход</a>
        <a href="{% url 'users:register' %}" class="p-2 btn btn-outline-primary">Регистрация</a>
    {% endif %}
</nav>

catalog/templates/catalog/includes/inc_product_form.html
<div class="col-3">
    <div class="card mb-4 box-shadow">
        <div class="card-header">
            <h4 class="my-0 font-weight-normal">{{ object.name }}</h4>
        </div>
        <div class="card-body">
            <h1 class="card-title pricing-card-title">RUR {{ object.price }}</h1>
            <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                <li> {{ object.description|truncatechars:50 }} </li>
            </ul>
            <a class="btn btn-lg btn-block btn-outline-info"
               href="{% url 'catalog:product_detail' object.pk %}">Информация</a>
            {% if user.is_authenticated and object.creator == user or perms.catalog.change_product %}
                <a class="btn btn-lg btn-block btn-outline-info"
                   href="{% url 'catalog:version_detail' object.pk|default:"url 'catalog:product_update'" %}">Версия</a>
                <a class="btn btn-lg btn-block btn-outline-warning"
                   href="{% url 'catalog:product_update' object.pk %}">Изменить/Удалить</a>
            {% endif %}


            <button type="button" class="btn btn-lg btn-block btn-outline-success">Купить</button>
        </div>
    </div>
</div>